version: '2'

services:
  jenkins:      
    build: .
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/docker/certs:/docker_certs
    environment:
      VIRTUAL_HOST: tools.dc1.local,jenkins.buckingham.io
      VIRTUAL_PORT: 8080
      JAVA_OPTS: -Djava.awt.headless=true
    restart: always
    privileged: true

volumes:
  jenkins_home:

networks:
  default:
    external:
      name: nginx-proxy  
